
UPDATE table_1 SET Ap='MU?OZ' WHERE Ap='MU';
UPDATE table_1 SET Am='MU?OZ' WHERE Am='MU';

UPDATE table_1 SET Ap='SALDA?A' WHERE Ap='SALDA';
UPDATE table_1 SET Am='SALDA?A' WHERE Am='SALDA';

UPDATE table_1 SET Ap='PE?A' WHERE Ap='PE';
UPDATE table_1 SET Am='PE?A' WHERE Am='PE';

UPDATE table_1 SET Ap='NU?EZ' WHERE Ap='NU';
UPDATE table_1 SET Am='NU?EZ' WHERE Am='NU';

UPDATE table_1 SET Ap='MONTA?O' WHERE Ap='MONTA';
UPDATE table_1 SET Am='MONTA?O' WHERE Am='MONTA';

UPDATE table_1 SET Ap='SALDA?A' WHERE Ap='SALDA';
UPDATE table_1 SET Am='SALDA?A' WHERE Am='SALDA';

UPDATE table_1 SET Ap='ORDO?EZ' WHERE Ap='ORDO';
UPDATE table_1 SET Am='ORDO?EZ' WHERE Am='ORDO';

UPDATE table_1 SET Ap='CARCA?O' WHERE Ap='CARCA';
UPDATE table_1 SET Am='CARCA?O' WHERE Am='CARCA';

UPDATE table_1 SET Ap='OCA?A' WHERE Ap='OCA';
UPDATE table_1 SET Am='OCA?A' WHERE Am='OCA';

UPDATE table_1 SET Ap='CARRE?O' WHERE Ap='CARRE';
UPDATE table_1 SET Am='CARRE?O' WHERE Am='CARRE';

UPDATE table_1 SET Ap='CASTA?EDA' WHERE Ap='CASTA';
UPDATE table_1 SET Am='CASTA?EDA' WHERE Am='CASTA';

UPDATE table_1 SET Ap='YA?EZ' WHERE Ap='YA';
UPDATE table_1 SET Am='YA?EZ' WHERE Am='YA';

UPDATE table_1 SET Ap='CABA?AS' WHERE Ap='CABA';
UPDATE table_1 SET Am='CABA?AS' WHERE Am='CABA';

UPDATE table_1 SET Ap='RICA?O' WHERE Ap='RICA';
UPDATE table_1 SET Am='RICA?O' WHERE Am='RICA';

UPDATE table_1 SET Ap='BARRA?ON' WHERE Ap='BARRA';
UPDATE table_1 SET Am='BARRA?ON' WHERE Am='BARRA';

UPDATE table_1 SET Ap='AVENDA?O' WHERE Ap='AVENDA';
UPDATE table_1 SET Am='AVENDA?O' WHERE Am='AVENDA';

UPDATE table_1 SET Ap='VIA?A' WHERE Ap='VIA';
UPDATE table_1 SET Am='VIA?A' WHERE Am='VIA';

//Extras
update table_1 SET Am='PI?ON' WHERE Ficha='TLXEMS16/017763';
update table_1 SET Ap='BA?OS' WHERE Ficha='TLXEMS16/016310';
update table_1 SET Am='BA?UELAS' WHERE Ficha='TLXEMS16/021098';

UPDATE table_1 SET Ap='PI?A' WHERE Ap='PI'; 
UPDATE table_1 SET Am='PI?A' WHERE Am='PI';

UPDATE table_1 SET Ap='BA?UELOS' WHERE Ap='BA'; 
UPDATE table_1 SET Am='BA?UELOS' WHERE Am='BA';
